version: '3.8'

services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    user: "0:0"
    restart: unless-stopped
    volumes:
      - ./grafana/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - prometheus_data:/prometheus
    networks:
      cloud_internal:
        aliases:
          - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M


  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana_data:/var/lib/grafana:Z
    networks:
      cloud_internal:
        aliases:
          - grafana
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  prometheus_data:
  grafana_data:

networks:
  cloud_internal:
    external: true
  