services:
  nextcloud-db:
    image: docker.io/library/mariadb:10.11
    container_name: nextcloud-db
    user: "0:0"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${NC_DB_ROOT_PASS}
      - MARIADB_PASSWORD=${NC_DB_PASS}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
    volumes:
      - nextcloud_db_data:/var/lib/mysql:Z
    networks:
      - cloud_internal
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 256M

  nextcloud-app:
    image: docker.io/library/nextcloud:latest
    container_name: nextcloud-app
    user: "0:0"
    restart: always
    depends_on:
      - nextcloud-db
    environment:
      - MYSQL_PASSWORD=${NC_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db:3306
    volumes:
      - nextcloud_data:/var/www/html:Z
    networks:
      - cloud_public
      - cloud_internal
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1.5G
        reservations:
          memory: 512M
    security_opt:
      - "label=disable"

volumes:
  nextcloud_db_data:
  nextcloud_data:

networks:
  cloud_public:
    external: true
  cloud_internal:
    external: true
