version: "3.8"

services:
  tailscale-vpn:
    image: docker.io/tailscale/tailscale:latest
    container_name: tailscale_exit_node
    hostname: cloud-vpn-exit
    user: "0:0"
    restart: unless-stopped
    privileged: true
    networks:
      - tailscale_net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 64M
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-dns=true --ssh
    volumes:
      - tailscale_state:/var/lib/tailscale:Z
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    security_opt:
      - label:disable
      - seccomp=unconfined

volumes:
  tailscale_state:

networks:
  tailscale_net:
    driver: bridge
    external: true
