services:
  palisch-bot:
    image: registry.gitlab.com/fluffypal/palisch/main
    container_name: palisch-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${PALISCH_DISCORD_BOT}
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
