services:
  mattermost-db:
    image: docker.io/library/postgres:18-alpine
    container_name: mattermost-db
    user: "0:0"
    restart: always
    environment:
      - POSTGRES_USER=${MM_DB_USER}
      - POSTGRES_PASSWORD=${MM_DB_PASS}
      - POSTGRES_DB=${MM_DB_NAME}
    volumes:
      - mattermost_db_data:/var/lib/postgresql/data:Z
    networks:
      - cloud_internal
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  mattermost-app:
    image: docker.io/mattermost/mattermost-team-edition:latest
    container_name: mattermost-app
    restart: always
    depends_on:
      - mattermost-db
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MM_DB_USER}:${MM_DB_PASS}@mattermost-db:5432/${MM_DB_NAME}?sslmode=disable&connect_timeout=10

      - MM_SERVICESETTINGS_SITEURL=${MM_SITE_URL}
    volumes:
      - mattermost_data:/mattermost/data:Z
      - mattermost_logs:/mattermost/logs:Z
      - mattermost_config:/mattermost/config:Z
      - mattermost_plugins:/mattermost/plugins:Z
      - mattermost_client_plugins:/mattermost/client/plugins:Z
      - mattermost_bleve_indexes:/mattermost/bleve-indexes:Z
    networks:
      - cloud_public
      - cloud_internal
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    security_opt:
      - "label=disable"
    user: "2000:2000"

volumes:
  mattermost_db_data:
  mattermost_data:
  mattermost_logs:
  mattermost_config:
  mattermost_plugins:
  mattermost_client_plugins:
  mattermost_bleve_indexes:

networks:
  cloud_public:
    external: true
  cloud_internal:
    external: true
