services:
  icelatte:
    image: registry.gitlab.com/flaouve/discord-bot/icelatte:latest
    container_name: icelatte-bot
    restart: unless-stopped
    environment:
      - TOKEN=${ICELATTE_DISCORD_BOT}
      - DEBUG=${ICELATTE_DEBUG}
    volumes:
      - icelatte_db:/app/database:Z
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M

volumes:
  icelatte_db:
