services:
  littlelink-app:
    build:
      context: ./littlelink/.
      dockerfile: Dockerfile
      args:
        repo: ${LITTLELINK_GIT_REPO:-https://github.com/FuffyPal/littlelink.git}
    container_name: littlelink-app
    user: "0:0"
    restart: unless-stopped
    networks:
      - cloud_public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
networks:
  cloud_public:
    external: true
